// components/skill-item.vue
<script setup lang="ts">
    const values: Record<number, string> = {
        1: 'Beginner',
        2: 'Intermediate',
        3: 'Advanced',
        4: 'Expert',
        5: 'N/A'
    }

    const props = defineProps({
        name: {
            type: String,
            default: ''
        },
        value: {
            type: Number,
            default: 1
        }
    });
</script>

<template>
<li v-once class="flex px-1 item">
    <div class="flex flex-col w-full">
        <span class="text-sm tracking-wider text-gray-800">{{ props.name }}</span>
        <span class="text-sm tracking-wider text-slate-500">{{ values[props.value] }}</span>
    </div>
</li>
</template>

// app/components/basic/SkillItem.tsx
export type SkillItemProps = {
    name: string,
    value: number
}

const SkillsLevels: Record<number, string> = {
    1: 'Beginner',
    2: 'Intermediate',
    3: 'Advanced',
    4: 'Expert',
    5: 'N/A'
}

export default function SkillsItem({ name, value }: SkillItemProps) {
    return (
        <li className="flex px-1 item">
            <div className="flex flex-col w-full">
                <span className="text-sm tracking-wider text-gray-800">{name}</span>
                <span className="text-sm tracking-wider text-slate-500">{SkillsLevels[value]}</span>
            </div>
        </li>
    )
}
