// app/routes/register/index.tsx
import TopBar from "~/components/TopBar";
import ContactSection from "~/components/registerFeature/ContactSection";
import LocationSection from "~/components/registerFeature/LocationSection";
import EducationSection from "~/components/registerFeature/EducationSection";
import SkillSection from "~/components/registerFeature/SkillSection";
import PrivacySection from "~/components/registerFeature/PrivacySection";
import AvailabilitySection from "~/components/registerFeature/AvailabilitySection";
import ExperienceSection from "~/components/registerFeature/ExperienceSection";

export default function () {
    return (
        <div>
            <TopBar />
            {/* <ContactSection />
            <LocationSection />
            <EducationSection />
            <ExperienceSection />
            <SkillSection /> */}
            <PrivacySection />
            {/* <AvailabilitySection /> */}
        </div>
    )
}

// pages/register/index.vue
<script setup lang="ts">
    import ContactSection from "~/components/register/contact-section.vue"
    import LocationSection from "~/components/register/location-section.vue"
    import EducationSection from "~/components/register/education-section.vue"
    import ExperienceSection from "~/components/register/experience-section.vue"
    import TopBar from "~/components/top-bar.vue"
</script>

<template>
    <top-bar />
    <!-- <contact-section />     -->
    <!-- <location-section /> -->
    <!-- <education-section/> -->
    <experience-section />
</template>
