// components/top-bar.vue
<script setup lang="ts">
    import { Icons } from '~/lib/icons';
</script>

<template>
    <header id="topbar" class="flex bg-white sticky -top-1 py-2 z-50">
        <div class="flex flex-1 items-center px-3 lg:px-16 justify-between">
            <NuxtLink to="/">
                <img :src="Icons.LOGO" alt="logo" />
            </NuxtLink>

            <a href="#" class="flex items-center gap-1 w-[70px]">
                <img :src="Icons.USER" alt="user" width="24" height="24" />
                <span class="text-sm">Log in</span>
            </a>
        </div>
    </header>
</template>

// app/components/templates/TopBar.tsx
import { Icons } from "~/components/basic/Icons";

export default function TopBar(): JSX.Element {
    return (
        <header className="bg-white flex items-center justify-between h-14 px-8">
            <div className="">
                <img src="/img/getrez-logo.png" alt="logo" width={175} height={59} />
            </div>

            <a href="#" className="flex gap-2">
                <img src={Icons.Users} alt="icon" width={24} height={24} />
                <span className="text-base">Log in</span>
            </a>
        </header>
    )
}
