// app/components/ProjectItem.tsx
import { Badge } from "./basic/Badge"

export type ProjectItemProps = {
    name: string,
    description: string,
    stack: string[]
}

export default function ProjectItem( {name, description, stack}: ProjectItemProps){
    return(
        <div className="flex flex-col p-3 border-t-2">
        <h3 className="font-bold">{name}</h3>
        <p className="text-sm leading-5 text-slate-500">{description}</p>
        <div className="flex flex-wrap gap-2 py-2">
            {stack.map( (item,index) => (
                <Badge name={item} key={index} />
            ))}
        </div>
    </div>
    )
}

// components/project-item.vue
<script setup lang="ts">
    type Project = {
        name: string,
        description: string,
        stack: string[]
    }

    const props = defineProps({
        data: {
            type: Object as PropType<Project>,
            default: {}
        }
    })
</script>

<template>
    <div class="flex flex-col p-3 border-t-1">
        <h3 class="font-bold">{{ props.data.name }}</h3>
        <p class="text-sm leading-5 text-slate-500">{{ props.data.description }}</p>
        <div class="flex flex-wrap gap-2 py-2">
            <Badge v-for="item in props.data.stack" :name="item" />
        </div>
    </div>
</template>
