// app/components/basic/GrSelect.tsx
export type GrSelectProps = {
    id: string,
    placeholder: string,
    list:  Record<string, string>[],
}

export default function GrSelect({id, placeholder, list}: GrSelectProps){
    return (
        <select id={id} className="gr-select">
            <option  value="" disabled selected hidden>{placeholder}</option>
            {list.map( (item, index) => (
                <option value={item.key} key={index}>{item.value}</option>
            ))}
        </select>
    )
}

// components/atoms/gr-select.vue
<script setup lang="ts">
const props = defineProps({
    option: {
        type: String,
        default: 'Option'
    }
})
</script>
<template>
    <select required class="w-full h-12 bg-transparent border border-slate-400 rounded-md">
        <option  value="" disabled selected hidden>Select a {{option}}</option>
    </select>
</template>
